name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: auto
        description: "Use auto to automatically calculate version"

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@f2b5acd5d8d65e876631061bbc6240ee51c31df0 # 2.0.5
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
